# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_de_la_contratacion', models.CharField(max_length=100)),
                ('modalidad_de_contratacion', models.CharField(max_length=100)),
                ('entidad_contratante', models.CharField(max_length=100)),
                ('ec_telefono', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El telefono tiene un maximo de 8 dijitos', regex='^[0-9]{7,8}$')])),
                ('ec_direccion', models.CharField(max_length=50)),
                ('ec_email', models.EmailField(max_length=254)),
                ('fecha_inicio', models.DateField()),
                ('plaso_previsto', models.DateField()),
                ('ubicacion_proyecto', models.CharField(choices=[('PT', 'Potosi'), ('LP', 'La Paz'), ('CO', 'Cochabamba'), ('CH', 'Chuquisaca'), ('TA', 'Tarija'), ('OR', 'Oruro'), ('SC', 'Santa Cruz'), ('BE', 'Beni'), ('PA', 'Pando')], max_length=2)),
                ('presupuesto_final', models.FloatField()),
            ],
        ),
    ]
