# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_inicio', models.DateField()),
                ('plaso_previsto', models.DateField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.proyecto')),
            ],
            options={
                'verbose_name_plural': 'adtividades',
            },
        ),
    ]
