# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('plaso_finalisacion', models.DateField()),
                ('unidad', models.CharField(max_length=3)),
                ('cantidad', models.PositiveIntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.proyecto')),
            ],
            options={
                'verbose_name_plural': 'items',
            },
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='actividad',
        ),
    ]
