# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_auto_20160918_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='proyecto',
            new_name='proyecto_fk',
        ),
    ]
