# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_auto_20161001_1406'),
        ('seguimiento', '0005_auto_20160918_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='peticion_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
                ('itemsAlmacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.itemsAlmacen')),
            ],
        ),
    ]
