# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0017_auto_20161005_1922'),
        ('seguimiento', '0008_peticion_material_precio_estimado'),
    ]

    operations = [
        migrations.CreateModel(
            name='peticion_insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_estimado_total', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.insumos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
            ],
        ),
        migrations.RenameField(
            model_name='peticion_material',
            old_name='precio_estimado',
            new_name='precio_estimado_total',
        ),
    ]
