# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0010_auto_20161006_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='requerimiento_maq_he',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maq_he', models.CharField(max_length=60)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_estimado_total', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
            ],
        ),
        migrations.CreateModel(
            name='requerimientoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=60)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_estimado_total', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
            ],
        ),
    ]
