# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0012_auto_20161009_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='plaso_finalisacion',
            new_name='plazo_finalisacion',
        ),
    ]
