# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0013_auto_20161009_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='plazo_finalisacion',
            new_name='plazo_finalizacion',
        ),
    ]
