# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0014_auto_20161009_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='materiales_locales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='requerimiento_maq_he',
            name='precio_estimado_total',
        ),
        migrations.RemoveField(
            model_name='requerimientopersonal',
            name='precio_estimado_total',
        ),
        migrations.AddField(
            model_name='requerimiento_maq_he',
            name='precio_total',
            field=models.FloatField(default=(60.0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimientopersonal',
            name='precio_total',
            field=models.FloatField(default=(60.0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peticion_insumos',
            name='precio_estimado_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='peticion_materiales',
            name='precio_estimado_total',
            field=models.FloatField(),
        ),
    ]
