# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0015_auto_20161012_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requerimientoPersonal',
            new_name='requerimiento_personal',
        ),
    ]
