# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0019_salidaherramientas'),
        ('seguimiento', '0016_auto_20161012_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='peticion_Herramientas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('herramientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.herramientas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
            ],
        ),
    ]
