# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0020_reportes_avance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unidad',
            field=models.CharField(choices=[('Gbl', 'Gbl'), ('m2', 'm2'), ('m3', 'm3')], max_length=3),
        ),
    ]
