# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0023_reporte_fotografico_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes_avance',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
