# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0024_reportes_avance_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes_avance',
            name='alto',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0001, 'El valor no puede ser cero')]),
        ),
        migrations.AlterField(
            model_name='reportes_avance',
            name='ancho',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0001, 'El valor no puede ser cero')]),
        ),
        migrations.AlterField(
            model_name='reportes_avance',
            name='largo',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0001, 'El valor no puede ser cero')]),
        ),
    ]
