# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0025_auto_20161022_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion_herramientas',
            name='petion_de_planificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peticion_insumos',
            name='petion_de_planificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peticion_maquinaria_equipo',
            name='petion_de_planificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peticion_materiales',
            name='petion_de_planificacion',
            field=models.BooleanField(default=False),
        ),
    ]
