# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0026_auto_20161022_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales_locales',
            name='planificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requerimiento_maq_he',
            name='planificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requerimiento_personal',
            name='planificacion',
            field=models.BooleanField(default=False),
        ),
    ]
