# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0028_materiales_locales_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pocentaje_avance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
