# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0029_item_pocentaje_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='pocentaje_avance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
