# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0030_proyecto_pocentaje_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto_final',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10000, 'El presupuesto minimo de un proyecto esta por ensima de los 10000')]),
        ),
    ]
