# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 18:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0033_auto_20170512_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='La descripcion del item no es valido', regex='^(([a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ]{2,} )||([a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='materiales_locales',
            name='descripcion',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='La descripcion del material no es valida', regex='^(([a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ]{2,} )||([a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='entidad_contratante',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El nombre de la entidad no es valido', regex='^(([a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ]{2,} )||([a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modalidad_de_contratacion',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El tipo de modalidad no es valido', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='objeto_de_la_contratacion',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El objeto de la contratacion del proyecto no es valido', regex='^(([a-zA-Z0-9ZñÑáéíóúÁÉÍÓÚ]{2,} )||([a-zA-Z0-9ZñÑáéíóúÁÉÍÓÚ]{2,}))+$')]),
        ),
        migrations.AlterField(
            model_name='requerimiento_maq_he',
            name='nombre_maq_he',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='La descripcion de la maquinaria/equipo no es valida', regex='^(([a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ]{2,} )||([a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ]{2,}))+$')]),
        ),
    ]
