# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 21:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemsAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decripcion', models.CharField(max_length=100)),
                ('tipo_item', models.CharField(max_length=2)),
                ('cantidad', models.IntegerField(choices=[('MA', 'Material'), ('He', 'Herramienta'), ('EQ', 'Equipo'), ('IN', 'Insumo')])),
                ('unidad', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'item Almacen',
                'verbose_name_plural': 'items Almacen',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rason_social', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El telefono tiene un maximo de 8 dijitos', regex='^[0-9]{7,8}$')])),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
    ]
