# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 18:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_auto_20161001_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='ubicacion',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='almacen',
            name='ciudad',
            field=models.CharField(choices=[('PT', 'Potosi'), ('LP', 'La Paz'), ('CO', 'Cochabamba'), ('CH', 'Chuquisaca'), ('TA', 'Tarija'), ('OR', 'Oruro'), ('SC', 'Santa Cruz'), ('BE', 'Beni'), ('PA', 'Pando')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='telefono',
            field=models.PositiveIntegerField(default=72435587, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El telefono tiene un maximo de 8 dijitos', regex='^[0-9]{7,8}$')]),
            preserve_default=False,
        ),
    ]
