# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_auto_20161001_1716'),
        ('seguimiento', '0007_auto_20161001_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemsAlmacen',
        ),
        migrations.RemoveField(
            model_name='ingreso_material',
            name='itemsAlmacen',
        ),
        migrations.AddField(
            model_name='ingreso_material',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacenes.material'),
            preserve_default=False,
        ),
    ]
