# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0007_auto_20161002_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='herramientas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decripcion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
