# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0008_auto_20161003_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='herramientasAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('herramientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.herramientas')),
            ],
        ),
        migrations.AlterField(
            model_name='ingreso_material',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
