# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0009_auto_20161003_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso_material',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
