# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0011_auto_20161003_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresoHerramientas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('herramientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.herramientas')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.proveedor')),
            ],
        ),
    ]
