# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_peticion_material_precio_estimado'),
        ('almacenes', '0012_ingresoherramientas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresoInsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decripcion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='insumosAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.insumos')),
            ],
        ),
        migrations.AddField(
            model_name='ingresoinsumos',
            name='insumos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.insumos'),
        ),
        migrations.AddField(
            model_name='ingresoinsumos',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item'),
        ),
        migrations.AddField(
            model_name='ingresoinsumos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='insumosalmacen',
            unique_together=set([('almacen', 'insumos')]),
        ),
    ]
