# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_peticion_material_precio_estimado'),
        ('almacenes', '0013_auto_20161003_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='salidaInsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.insumos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
            ],
        ),
        migrations.AddField(
            model_name='ingresoinsumos',
            name='costo_total',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
