# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_peticion_material_precio_estimado'),
        ('almacenes', '0014_auto_20161003_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='salidaMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.material')),
            ],
        ),
        migrations.RenameModel(
            old_name='ingreso_material',
            new_name='materialAlmacen',
        ),
        migrations.AlterUniqueTogether(
            name='herramientasalmacen',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='herramientasalmacen',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='herramientasalmacen',
            name='herramientas',
        ),
        migrations.DeleteModel(
            name='herramientasAlmacen',
        ),
    ]
