# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0017_auto_20161005_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='herramientasAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('herramientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.herramientas')),
            ],
        ),
        migrations.AddField(
            model_name='ingresoherramientas',
            name='costo_total',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresoherramientas',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='herramientasalmacen',
            unique_together=set([('almacen', 'herramientas')]),
        ),
    ]
