# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0016_auto_20161012_1840'),
        ('almacenes', '0018_auto_20161013_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='salidaHerramientas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debuelto', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('herramientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.herramientas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
            ],
        ),
    ]
