# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0019_salidaherramientas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresoMaquinaria_equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('costo_total', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='maquinaria_equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decripcion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='maquinaria_equipoAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('maquinaria_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.maquinaria_equipo')),
            ],
        ),
        migrations.AddField(
            model_name='ingresomaquinaria_equipo',
            name='maquinaria_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.maquinaria_equipo'),
        ),
        migrations.AddField(
            model_name='ingresomaquinaria_equipo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='maquinaria_equipoalmacen',
            unique_together=set([('almacen', 'maquinaria_equipo')]),
        ),
    ]
