# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0017_peticion_herramientas'),
        ('almacenes', '0020_auto_20161013_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='salidaMaquinaria_equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debuelto', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.item')),
                ('maquinaria_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.maquinaria_equipo')),
            ],
        ),
    ]
