# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0022_herramientas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria_equipo',
            name='tipo',
            field=models.CharField(default='liviana', max_length=30),
            preserve_default=False,
        ),
    ]
