# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0023_maquinaria_equipo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainsumos',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
