# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0024_auto_20161027_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('fecha_ingreso', models.DateField()),
                ('costo_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('años_vida_util', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='tipoActivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.tipoActivo'),
        ),
    ]
