# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 20:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0027_auto_20170420_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoherramientas',
            name='no_factura',
            field=models.PositiveIntegerField(default=6672252, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de factura tiene de 5 a 20 cifras', regex='^[0-9]{7,8}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresoinsumos',
            name='no_factura',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de factura tiene de 5 a 20 cifras', regex='^[0-9]{7,8}$')]),
        ),
        migrations.AlterField(
            model_name='ingresomaterial',
            name='no_factura',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de factura tiene de 5 a 20 cifras', regex='^[0-9]{7,8}$')]),
        ),
    ]
