# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0030_auto_20170512_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(default='6672252', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El telefono tiene un maximo de 8 dijitos', regex='^[0-9]{7,12}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresoherramientas',
            name='no_factura',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de factura tiene de 5 a 20 cifras', regex='^[0-9]{1,20}$')]),
        ),
        migrations.AlterField(
            model_name='ingresoinsumos',
            name='no_factura',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de factura tiene de 5 a 20 cifras', regex='^[0-9]{1,20}$')]),
        ),
        migrations.AlterField(
            model_name='ingresomaterial',
            name='no_factura',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de factura tiene de 5 a 20 cifras', regex='^[0-9]{1,20}$')]),
        ),
    ]
