# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 18:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0031_auto_20170519_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoinsumos',
            name='no_autorizacion',
            field=models.CharField(default='0001235', max_length=50, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de autorizacion tiene de 5 a 20 cifras', regex='^[0-9]{5,20}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresomaterial',
            name='no_autorizacion',
            field=models.CharField(default='0001235', max_length=50, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de autorizacion tiene de 5 a 20 cifras', regex='^[0-9]{5,20}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresoinsumos',
            name='no_factura',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de factura tiene de 1 a 20 cifras', regex='^[0-9]{1,20}$')]),
        ),
        migrations.AlterField(
            model_name='ingresomaterial',
            name='no_factura',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='El numero de factura tiene de 1 a 20 cifras', regex='^[0-9]{1,20}$')]),
        ),
    ]
