# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 18:35
from __future__ import unicode_literals

import apps.personal.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=9, unique=True, validators=[[django.core.validators.RegexValidator(code='Numero Invalido', message='El ci Tiene un Maximo de 7 Digitos', regex='[0-9]{7}[a-zA-Z]{0,2}')]])),
                ('telefono_fijo', models.PositiveIntegerField(validators=[[django.core.validators.RegexValidator(code='Numero Invalido', message='El celular tiene un maximo de 8 dijitos', regex='^[0-9]{7,8}$')]])),
                ('celular', models.PositiveIntegerField(validators=[[django.core.validators.RegexValidator(code='Numero Invalido', message='El celular tiene un maximo de 8 dijitos', regex='^[0-9]{8}$')]])),
                ('curriculum', models.FileField(upload_to='curriculums/', validators=[apps.personal.models.validate_file_extension])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
