# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:16
from __future__ import unicode_literals

import apps.personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20160818_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/', validators=[apps.personal.models.validate_file_extension]),
        ),
    ]
