# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguimiento', '0005_auto_20160918_1740'),
        ('personal', '0003_auto_20160912_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='designacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.cargo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
