# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_designacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='codigo_cargo',
        ),
    ]
