# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_cargo_codigo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacion',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.proyecto'),
        ),
    ]
