# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20160924_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacion',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.cargo'),
        ),
    ]
