# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_auto_20160918_1740'),
        ('personal', '0012_auto_20160924_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='designacion_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='designacion_cargo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='designacion_cargo',
            name='designacion',
        ),
        migrations.RemoveField(
            model_name='designacion',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='designacion',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.cargo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='designacion_cargo',
        ),
        migrations.AddField(
            model_name='designacion_proyecto',
            name='designacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.designacion'),
        ),
        migrations.AddField(
            model_name='designacion_proyecto',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.proyecto'),
        ),
    ]
