# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_auto_20160924_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designacion',
            name='cargo',
        ),
        migrations.AddField(
            model_name='designacion_proyecto',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.cargo'),
            preserve_default=False,
        ),
    ]
