# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_auto_20160918_1740'),
        ('personal', '0017_auto_20160924_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designacion_proyecto',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='designacion_proyecto',
            name='designacion',
        ),
        migrations.RemoveField(
            model_name='designacion_proyecto',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='designacion',
            name='cargo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designacion',
            name='proyecto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designacion',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='designacion_proyecto',
        ),
    ]
