# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_auto_20160924_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.proyecto'),
        ),
    ]
