# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0023_auto_20161001_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardex',
            old_name='profecion',
            new_name='profesion',
        ),
    ]
