# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0024_auto_20161009_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='encargado_de_reportes_avance',
            field=models.BooleanField(default=False),
        ),
    ]
