# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0025_cargo_encargado_de_reportes_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1800, 'El salario minimo nacional es 1800')]),
        ),
    ]
