# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0028_auto_20170518_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='minnacional',
            name='actualisar_sueldos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.FloatField(),
        ),
    ]
