# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0029_auto_20170518_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minnacional',
            name='minimo_nacional',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000, 'El salario minimo en el pais actualmente no es por debajo de los 1000 Bs')]),
        ),
    ]
